{% set version = '1.3-18' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pastecs
  version: {{ version|replace("-", "_") }}

source:
  fn: pastecs_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pastecs_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pastecs/pastecs_{{ version }}.tar.gz


  sha256: 5188662294bf91545d0c2e4d7de113296f5a8c2cbf38bdc2a90f3f7d03b3b447
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-boot

  run:
    - r-base
    - r-boot

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pastecs')"  # [not win]
    - "\"%R%\" -e \"library('pastecs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http
  license: GPL (>= 2)
  summary: Regulation, decomposition and analysis of space-time series. The pastecs library is
    a PNEC-Art4 and IFREMER (Benoit Beliaeff <Benoit.Beliaeff@ifremer.fr>) initiative
    to bring PASSTEC 2000 (http
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: pastecs
# Title: Package for Analysis of Space-Time Ecological Series
# Version: 1.3-18
# Date: 2014-03-02
# Author: Philippe Grosjean [aut, cre], Frederic Ibanez [aut], Michele Etienne [ctb]
# Authors@R: c(person("Philippe", "Grosjean", role = c("aut", "cre"), email = "phgrosjean@sciviews.org"), person("Frederic", "Ibanez", role = "aut", email = "ibanez@obs-vlfr.fr"), person("Michele", "Etienne", role = "ctb", email = "etienne@obs-vlfr.fr"))
# Maintainer: Philippe Grosjean <phgrosjean@sciviews.org>
# Description: Regulation, decomposition and analysis of space-time series. The pastecs library is a PNEC-Art4 and IFREMER (Benoit Beliaeff <Benoit.Beliaeff@ifremer.fr>) initiative to bring PASSTEC 2000 (http://www.obs-vlfr.fr/~enseigne/anado/passtec/passtec.htm) functionalities to R.
# URL: http://www.sciviews.org/pastecs
# Encoding: latin1
# License: GPL (>= 2)
# Depends: boot, stats
# Packaged: 2014-03-02 12:35:27 UTC; phgrosjean
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-03-02 14:01:51

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
