# GNU Parallel
# updated to latest from https://github.com/ostrokach/conda-recipes-extra/tree/master/parallel

package:
  name: parallel
  version: 20170322

source:
  url: http://mirror.frgl.pw/gnu/parallel/parallel-20170322.tar.bz2
  fn: parallel-20170322.tar.bz2
  md5: 4fe1b8d2e3974d26c77f0b514988214d

build:
  number: 2

requirements:
  build:
  run:
    - perl

test:
  commands:
    - parallel --version

about:
  home: http://www.gnu.org/software/parallel/
  license: GPLv3
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers.
